/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.posgen;

import java.sql.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author ben
 */
public class Daily_inventory extends javax.swing.JDialog {

    Connection con=null;
    PreparedStatement pst,pst1=null,pst2=null;
    ResultSet rst,rst1=null;
    String with,by,item;
         float units,cost=0,totalcost,number=0,remainingnumber,total_cost,new_total_cost;
        
    
    /**
     * Creates new form Daily_inventory
     */
    public Daily_inventory(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        connect connection =new connect();
        con=connection.connectdb();
        loadcombos();
        this.setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo_activity = new javax.swing.JComboBox<>();
        combo_item = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_units = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combo_by = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtf_with = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Daily Inventory");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Activity");

        combo_activity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Issue", "Receive" }));
        combo_activity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_activityActionPerformed(evt);
            }
        });

        combo_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select item" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Inventory Item");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Units In/Out");

        jtf_units.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_unitsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Transaction By");

        combo_by.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select item" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Transaction With");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.gif"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete16.gif"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_by, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_activity, 0, 182, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_units)
                            .addComponent(combo_item, 0, 182, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_with)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_activity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_item, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jtf_units, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_by, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtf_with, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_unitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_unitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_unitsActionPerformed

    private void combo_activityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_activityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_activityActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // cancel
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // save activity
         String activity=String.valueOf(combo_activity.getSelectedItem());
          units=Float.parseFloat(jtf_units.getText());
         by=String.valueOf(combo_by.getSelectedItem());
         with=jtf_with.getText();
         item=String.valueOf(combo_item.getSelectedItem());
        
         
        try {
            //get the total items in the database and the cost
            pst1=con.prepareStatement("select * from `inventory` where `inventory_item`='"+item+"'");
            rst1=pst1.executeQuery();
            while(rst1.next()){
                cost=rst1.getFloat("unit_cost");
                number=rst1.getFloat("number");
                total_cost=rst1.getFloat("total_cost");
            }
                
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane, ex);
        }
         
         if(activity.equalsIgnoreCase("Issue")){
          //   JOptionPane.showMessageDialog(rootPane, number+"units"+units+"remaining"+remainingnumber+"cost"+cost+"totalcost"+totalcost);
                
            try {
                totalcost=(units*cost);
                remainingnumber=(number-units);
                new_total_cost=(remainingnumber*cost);
                // JOptionPane.showMessageDialog(rootPane, remainingnumber+totalcost);
                 //now we update the 2 tables
                pst=con.prepareStatement("INSERT INTO `inventory_ops`( `item_name`, `units_in`, `units_out`, `remaining_units`, `Cost`,  `Transaction_by`, `Transaction_with`) VALUES (?,?,?,?,?,?,?)");
            
                pst.setString(1, item);
                pst.setFloat(2, 0);
                pst.setFloat(3, units);
                pst.setFloat(4,remainingnumber );
                pst.setFloat(5, new_total_cost);
                pst.setString(6, by);
                pst.setString(7, with);
               
                pst.execute();
                
                //updating the inventory
                
                pst2=con.prepareStatement("UPDATE `inventory` SET `number`=?,`total_cost`=? WHERE `inventory_item`=? ");
            pst2.setFloat(1, remainingnumber);
            pst2.setFloat(2, new_total_cost);
            pst2.setString(3, item);
            pst2.execute();
            JOptionPane.showMessageDialog(rootPane, "ITEM ISSUE RECORDED");
            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(rootPane, ex);
             }
         }else if(activity.equalsIgnoreCase("Receive")){
           totalcost=(units*cost);
                remainingnumber=(number+units);
                new_total_cost=(remainingnumber*cost); 
                try {
                  pst=con.prepareStatement("INSERT INTO `inventory_ops`( `item_name`, `units_in`, `units_out`, `remaining_units`, `Cost`,  `Transaction_by`, `Transaction_with`) VALUES (?,?,?,?,?,?,?)");
            
                pst.setString(1, item);
                pst.setFloat(2, 0);
                pst.setFloat(3, units);
                pst.setFloat(4,remainingnumber );
                pst.setFloat(5, new_total_cost);
                pst.setString(6, by);
                pst.setString(7, with);
               
                pst.execute();
                
                //updating the inventory
                
                pst2=con.prepareStatement("UPDATE `inventory` SET `number`=?,`total_cost`=? WHERE `inventory_item`=? ");
            pst2.setFloat(1, remainingnumber);
            pst2.setFloat(2, new_total_cost);
            pst2.setString(3, item);
            pst2.execute();
            JOptionPane.showMessageDialog(rootPane, "ITEM ADDED TO STOCK");
             } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
             }
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daily_inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daily_inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daily_inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daily_inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Daily_inventory dialog = new Daily_inventory(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_activity;
    private javax.swing.JComboBox<String> combo_by;
    private javax.swing.JComboBox<String> combo_item;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtf_units;
    private javax.swing.JTextField jtf_with;
    // End of variables declaration//GEN-END:variables
public void loadcombos(){
    //loadig the comboboxes
    try {
        pst=con.prepareStatement("select `inventory_item` from `inventory`");
        rst=pst.executeQuery();
        pst1=con.prepareStatement("select `user_name` from `employees` ");
        rst1=pst1.executeQuery();
        
        while(rst.next()){
            combo_item.addItem(rst.getString("inventory_item"));
        }
        while(rst1.next()){
            combo_by.addItem(rst1.getString("user_name"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
    finally{
        try {
            pst.close();
            rst.close();
            pst1.close();
            rst1.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
}
//update both tables

}
