/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates 
 * and open the template in the editor.
 */
package com.mycompany.posgen;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import javax.swing.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/*import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
*/



/**
 *
 * @author ben
 */
public class userinterface extends javax.swing.JFrame {
Connection con=null;
    PreparedStatement pst,pst1,pst2,pst3=null;
    ResultSet rst,rst1,rst2,rst3=null;
    String cat,clickedcat,clickedfood,food,product_name,product_category,unit_measure,id,id1,clickedid;
   Float totalcost,newcost,no,unit_cost,VAT,vatrate,vatcost;
    int count=0,i,j,zero=1,maxid1, maxid2,maxid3;
    public int maxid=0,counter=0;
    public double costsum=0.0;
    
    DefaultTableModel dtm1;
    login variable=new login(this, rootPaneCheckingEnabled);
       String sold_by=variable.getusername();
    
ResultSetMetaData rsmd,rsmd1=null;
    DefaultTableModel dtm=new DefaultTableModel();  
    
    
    /**
     * Creates new form userinterface
     */
    public userinterface() {
        initComponents();
        this.setLocationRelativeTo(this);
       connect connection=new connect();
        con=connection.connectdb();
        startthings();
       // printreceipt();
        
        
        
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 201, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DAILY SALES");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pick Category"));
        jPanel3.setAutoscrolls(true);
        jPanel3.setEnabled(false);
        jPanel3.setMaximumSize(new java.awt.Dimension(230, 350));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pick Food"));
        jPanel4.setMaximumSize(new java.awt.Dimension(484, 446));

        jPanel9.setEnabled(false);
        jPanel9.setMaximumSize(new java.awt.Dimension(484, 446));
        jPanel9.setPreferredSize(new java.awt.Dimension(484, 446));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(363, 363, 363))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(347, 347, 347))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Buttons"));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("CANCEL SALE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("CALCULATOR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("COMPLETE SALE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("CLOSE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setText("COMPLETE $ PAY");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addGap(146, 146, 146))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Bought items"));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTable3.setRowHeight(30);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("TOTAL AMOUNT   :");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setText("0.0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        //When on clicks on an item we want to delete it completely
     int row=jTable3.getSelectedRow();
     clickedid=jTable3.getModel().getValueAt(row, 0).toString();
    int choice=JOptionPane.showConfirmDialog(rootPane, "Confirm sale of item deletion","CONFIRM",0);
    if(choice==0){
         try {
             //we delete from the basket table and refresh table
           pst=con.prepareStatement("delete from `basket` where `id`='"+clickedid+"' ");
        pst.execute();
         populatejtable3();
             
         } catch (SQLException ex) {
             //Logger.getLogger(userinterface.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(rootPane, ex);
         }   }
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
        // cancel sale
      
        pst1=con.prepareStatement("delete from `basket` where `sale_id`='"+maxid+"'");
        pst1.execute();
        JOptionPane.showMessageDialog(rootPane, "sale cancelled");
         maxid=0;
         maxid1=0;
         startthings(); //initialize the maxid
    } catch (SQLException ex) {
        Logger.getLogger(userinterface.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     try {
         //complete sale without receiving cash
        // complete the cash sale bysaving all the items in the sales database and deleting from
        pst=con.prepareStatement("select * from `basket` where `sale_id`='"+maxid+"'");
       rst=pst.executeQuery();
       while(rst.next()){
           //now let us insert them
          
           pst1=con.prepareStatement("INSERT INTO `sales` (`sale_id`, `product_name`, `unit_cost`, `units_sold`, `total_cost`, `sale_by`,VAT)VALUES(?,?,?,?,?,?,?) ");
          pst1.setInt(1, Integer.valueOf(rst.getString("sale_id")));
           pst1.setString(2, rst.getString("product_name"));
            pst1.setFloat(3,Float.valueOf(rst.getString("unit_cost")) );
           pst1.setFloat(4,Float.valueOf(rst.getString("units_sold")) );
           pst1.setFloat(5,(Float.valueOf(rst.getString("price"))+Float.valueOf(rst.getString("VAT"))) );
           pst1.setString(6,rst.getString("sale_by") );
           pst1.setFloat(7, Float.valueOf(rst.getString("VAT")));
           pst1.execute();
       }
       
       subtractsold();
   printreceipt();  
   //go to the payments form
   //this.dispose();
   
    startthings();
    dtm.setRowCount(0);
    } catch (Exception ex) {
       JOptionPane.showMessageDialog(rootPane, ex);
               
    }
     finally{
         
         try{
            pst3=con.prepareStatement("delete from `basket` where `sale_id`='"+maxid+"'");
            pst3.execute();
         }catch(SQLException ex){
         JOptionPane.showMessageDialog(rootPane, ex);     
         }
     }
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//CLOSE THE JFRAME
this.dispose();
login show=new login(this, true);
show.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         // simple calculater
         SimpleCalc show=new SimpleCalc();
         show.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //LOgout button
        this.dispose();
        login show=new login(this, rootPaneCheckingEnabled);
        show.setVisible(rootPaneCheckingEnabled);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // complete sale and receive cash
        
        
        try {
        // complete the cash sale bysaving all the items in the sales database and deleting from
        pst=con.prepareStatement("select * from `basket` where `sale_id`='"+maxid+"'");
       rst=pst.executeQuery();
       while(rst.next()){
           //now let us insert them
          
           pst1=con.prepareStatement("INSERT INTO `sales` (`sale_id`, `product_name`, `unit_cost`, `units_sold`, `total_cost`, `sale_by`,VAT)VALUES(?,?,?,?,?,?,?) ");
          pst1.setInt(1, Integer.valueOf(rst.getString("sale_id")));
           pst1.setString(2, rst.getString("product_name"));
            pst1.setFloat(3,Float.valueOf(rst.getString("unit_cost")) );
           pst1.setFloat(4,Float.valueOf(rst.getString("units_sold")) );
            pst1.setFloat(5,(Float.valueOf(rst.getString("price"))+Float.valueOf(rst.getString("VAT"))) );
           pst1.setString(6,rst.getString("sale_by") );
           pst1.setFloat(7, Float.valueOf(rst.getString("VAT")));
           pst1.execute();
       }
        subtractsold();
   printreceipt();  
   //go to the payments form
   //this.dispose();
   ReceivePayment show=new ReceivePayment();
   show.setVisible(rootPaneCheckingEnabled);
   
   
    startthings();
    dtm.setRowCount(0);
    } catch (Exception ex) {
       JOptionPane.showMessageDialog(rootPane, ex);
               
    }
     finally{
         
         try{
            pst3=con.prepareStatement("delete from `basket` where `sale_id`='"+maxid+"'");
            pst3.execute();
         }catch(SQLException ex){
         JOptionPane.showMessageDialog(rootPane, ex);     
         }
     }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userinterface().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
 public void getcategories(int maxid){
 
    // jPanel8.setLayout(new GridBagLayout());
     jPanel8.setLayout(new GridLayout(0,3, 7, 7));
     jPanel3.setLayout(new GridLayout(1, 1));
 
    try {
        pst=con.prepareStatement("select * from `categories` ");
        rst=pst.executeQuery();
        
        while(rst.next()){
           count=count+1;
           cat=rst.getString("Category");
           JButton  b=new JButton(cat);
           b.setBackground(Color.red);
           
                jPanel8.add(b); 
            
           b.addActionListener(new ActionListener(){  
public void actionPerformed(ActionEvent e){  
     clickedcat=b.getActionCommand();
     //calling the individual foods within the selected category
     jPanel9.removeAll();
      getfoods(clickedcat,maxid);
}  
    }); 

b.addMouseListener(new MouseListener() {
               
               @Override
               public void mouseEntered(MouseEvent e) {
                 b.setBackground(Color.BLUE); 
               }

               @Override
               public void mouseExited(MouseEvent e) {
                  b.setBackground(Color.red);
               }

               @Override
               public void mouseClicked(MouseEvent e) {
               clickedcat=b.getActionCommand();
     //calling the individual foods within the selected category
     jPanel9.removeAll();
      getfoods(clickedcat,maxid);  
               }

               @Override
               public void mousePressed(MouseEvent e) {
              clickedcat=b.getActionCommand();
     //calling the individual foods within the selected category
     jPanel9.removeAll();
      getfoods(clickedcat,maxid);
               }

               @Override
               public void mouseReleased(MouseEvent e) {
               clickedcat=b.getActionCommand();
     //calling the individual foods within the selected category
     jPanel9.removeAll();
      getfoods(clickedcat,maxid);}
           });
           
        } 
    } catch (SQLException ex) {
        Logger.getLogger(userinterface.class.getName()).log(Level.SEVERE, null, ex);
    }
        
     jPanel8.revalidate();
       jPanel8.repaint();    
  
 
}
                public void getfoods(String clickedcat,int maxid){
                     //display the keyboard
                    // virtualkeyboard();
                    jPanel4.setLayout(new GridLayout(1,1));
                    jPanel9.setLayout(new GridLayout(0,5, 7, 7));
                    
                    changeid();
                  
                   try {
                       // a method to get the foods from the cicked category

                       pst=con.prepareStatement("SELECT * FROM `products` WHERE `product_category`='"+clickedcat+"' and `number`>=0 ");
                       rst=pst.executeQuery();
                       while(rst.next()){
                        product_name=rst.getString("product_name");
//                        unit_measure=rst.getString("unit_measure");
//                        unit_cost=rst.getFloat("unit_cost");
//                        id=rst.getString("id");
                                
                       
                        JButton  c=new JButton(product_name);
                          c.setBackground(Color.green);
                          jPanel9.add(c);
                          c.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                try {
                                    //when a food is clicked
                                    //first get the clicked food
                                    clickedfood=c.getActionCommand();
                                    //get the database values
                       pst1=con.prepareStatement("SELECT * FROM `products` WHERE `product_name`='"+clickedfood+"' ");
                       rst1=pst1.executeQuery();
                       while(rst1.next()){
                         product_name=rst1.getString("product_name");
                        unit_measure=rst1.getString("unit_measure");
                        unit_cost=rst1.getFloat("unit_cost");
                        id=rst1.getString("id"); 
                        vatrate=rst1.getFloat("VAT");
                        counter=Integer.valueOf(rst1.getString("number"));
                       } 
                       numberdialog get=new numberdialog(jFrame1, rootPaneCheckingEnabled);
                       get.setVisible(rootPaneCheckingEnabled);
                                  no=get.number; 
                               
                                   
                                    try {
                                        //making sure you do not sell more than stocks count
                                         if(no>counter){
                                         JOptionPane.showMessageDialog(rootPane, "The Stock has less than "+no+"  "+clickedfood+"s. Only  "+counter+" are present" );
                                         }else{
                                          //now multiply the numer  and cost to come up with the tottal cost
                                    totalcost=Float.valueOf(jTextField1.getText());
                                 //   newcost=((unit_cost*no)+totalcost);
                                 newcost=(unit_cost*no);
                          //VAT=Math.round(vatrate);
                                      VAT=(newcost*vatrate) ;
                                      //now lets insert into the basket
                                   // VAT=(unit_cost*no)
                                    pst3=con.prepareStatement("insert into `basket`(`sale_id`,`product_name`,`unit_cost`,`units_sold`,`price`,`sale_by`,`VAT`)values('"+maxid+"','"+product_name+"','"+unit_cost+"','"+no+"','"+newcost+"','"+sold_by+"','"+VAT+"')");
                                    pst3.execute();
                                    
                                    populatejtable3();
                                    
                                         }
                                        
                                    } catch (Exception err) {
                                        JOptionPane.showMessageDialog(rootPane, err);
                                    }
                                      
                                } catch (SQLException ex) {
                                   JOptionPane.showMessageDialog(rootPane, ex);}
                            }
                        });
                          
                       }
                       jPanel9.revalidate();
                      jPanel9.repaint();

                   } catch (SQLException ex) {
                       Logger.getLogger(userinterface.class.getName()).log(Level.SEVERE, null, ex);
                   }
                }
  
public void populatejtable3(){
    //this is to populate jTable 3
     dtm.setRowCount(0);
  try {
        // populate table1
    pst=con.prepareStatement("SELECT  *  FROM `basket` where `sale_id`='"+maxid+"'");
    pst.execute();
    rst=pst.executeQuery();
    rsmd=rst.getMetaData();
    int columns=rsmd.getColumnCount();
    Vector column_names=new Vector();
    Vector row_data=new Vector();
    for(i=1; i<=columns;i++){
    column_names.addElement(rsmd.getColumnName(i));
    }
    dtm.setColumnIdentifiers(column_names);
   while(rst.next()){
     row_data=new Vector();
     for(j=1;j<=columns;j++){
     row_data.addElement(rst.getString(j));
    }
     dtm.addRow(row_data);
    }
     jTable3.setModel(dtm);
     
     //lets now change the toal displayed  
     pst1=con.prepareStatement("select sum(`price`),sum(`VAT`) from `basket` where `sale_id`='"+maxid+"'");
     rst1=pst1.executeQuery();
     if(rst1.next()){
         jTextField1.setText(String.valueOf(Math.round(rst1.getFloat(1)+rst1.getFloat(2))));
         
     }
   
}   catch (SQLException ex) {
        Logger.getLogger(userinterface.class.getName()).log(Level.SEVERE, null, ex);
    }
}
        
public void startthings(){
     jPanel9.revalidate();
       jPanel9.repaint();
       
    try {
        
        pst1=con.prepareStatement("select max(`id`)from `sales` ");
        rst1=pst1.executeQuery();
        if(rst1.next()){
            maxid1=rst1.getInt(1);
            maxid=maxid1+1;
        }
       
//        pst=con.prepareStatement("insert into `sales`(`sale_id`,`product_name`,`unit_cost`,`units_sold`,`total_cost`)values('','','','','')");
//        pst.execute();
//remove objects from jpanels
jPanel8.removeAll();
jPanel9.removeAll();
 getcategories(maxid);
    } catch (SQLException ex) {
        Logger.getLogger(userinterface.class.getName()).log(Level.SEVERE, null, ex);
    }
}
public void changeid(){
    //this is a method to change maxid if another person has already locked it
    
    try {
        pst1=con.prepareStatement("select max(`id`)from `sales` ");
        rst1=pst1.executeQuery();
        if(rst1.next()){
            maxid2=rst1.getInt(1);
            maxid3=maxid2+1;
        }
if(maxid3==maxid){
   //nothing has changed
   maxid=maxid3;
}else{
    changeid();
}
    } catch (SQLException ex) {
        Logger.getLogger(userinterface.class.getName()).log(Level.SEVERE, null, ex);
    }
}
public void printreceipt(){
    //a function to print the receipt of a cash sale
/*try{
     
        JasperDesign jd=JRXmlLoader.load("C:\\Users\\posreport\\Documents\\reports\\genpos\\cashsale.jrxml");
        String sql="SELECT sales.`sale_id` AS sales_sale_id, sales.`product_name` AS sales_product_name, sales.`unit_cost` AS sales_unit_cost,sales.VAT AS sales_VAT, sales.`units_sold` AS sales_units_sold, sales.`total_cost` AS sales_total_cost, sales.`sale_by` AS sales_sale_by, sales.`date` AS sales_date FROM `sales` sales where sales.`sale_id`='"+maxid+"'";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);

            JasperReport jr=JasperCompileManager.compileReport(jd);
            JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
         // JasperViewer.viewReport(jp,false);
            JasperPrintManager.printReport(jp,false);
      
          
    }catch(JRException ex){
       
      JOptionPane.showMessageDialog(rootPane, ex);
    }
      
}
public void virtualkeyboard(){
    try{

 Runtime.getRuntime().exec("cmd /c osk");
   
          
    }catch(IOException ex){
        JOptionPane.showMessageDialog(rootPane, ex);
    }  */
}


public void subtractsold(){
    
    //subtract the units sold from the total 
  String product,units_sold,currentunits = null;
  Float remaining;
  
        try {
            //get the items from sales
            pst=con.prepareStatement("select * from `sales` where `sale_id`='"+maxid+"'");
            rst=pst.executeQuery();
            while(rst.next()){
             product=rst.getString("product_name");
             units_sold=rst.getString("units_sold");
             //how many are in stock
             pst2=con.prepareStatement("select `number` from `products` where `product_name`='"+product+"'");
             rst2=pst2.executeQuery();
             while(rst2.next()){
               currentunits=rst2.getString("number");
             }
             //change the stock amount
             remaining=(Float.valueOf(currentunits)-Float.valueOf(units_sold));
             //now lets update stock
             pst3=con.prepareStatement("update `products` set `number`='"+remaining+"' where `product_name`='"+product+"'");
             pst3.execute();
             
            }
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, ex);
        }
}

}
